#! /usr/bin/env python3

from argparse import ArgumentParser
from json import load, dump
import sys

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument('name', help='name of player')
    parser.add_argument('email', help="player's email address")
    parser.add_argument('-p', '--phone', help="player's phone number")
    args = parser.parse_args()
    
    with open('known_players.json', 'r') as known_players_file:
        known_players = load(known_players_file)

    player = {'email': args.email}
    if args.phone:
        player['phone'] = args.phone

    known_players[args.name] = player

    with open('known_players.json', 'w') as known_players_file:
        dump(known_players, known_players_file)
